const APP_SRC_FOLDER = 'src'
const APP_SOURSE_FOLDER_PATH = './src/SourceFolder'
const APP_RESULT_FOLDER = './src/ResultFolder'

const DESIGNER_FOLDER_PATH = '../../../iTech Offices/01 WSP_Desiners Schems'
const SERVER_BASE_PATH = '../server/WSP.WebAPI'
const SERVER_PREVIEWS_PATH = SERVER_BASE_PATH + '/Images/RoomPreviews'
const SERVER_ROOMS_PATH = SERVER_BASE_PATH + '/Json/Rooms'
const SERVER_FLOORS_PATH = SERVER_BASE_PATH + '/Json/Floors'

exports.DESIGNER_FOLDER_PATH = DESIGNER_FOLDER_PATH
exports.APP_SRC_FOLDER = APP_SRC_FOLDER
exports.APP_SOURSE_FOLDER_PATH = APP_SOURSE_FOLDER_PATH
exports.APP_RESULT_FOLDER = APP_RESULT_FOLDER
exports.SERVER_BASE_PATH = SERVER_BASE_PATH
exports.SERVER_PREVIEWS_PATH = SERVER_PREVIEWS_PATH
exports.SERVER_ROOMS_PATH = SERVER_ROOMS_PATH
exports.SERVER_FLOORS_PATH = SERVER_FLOORS_PATH

exports.folderPathes = [
	APP_SRC_FOLDER,
	APP_SOURSE_FOLDER_PATH,
	APP_RESULT_FOLDER,
]
